os: linux
dist: bionic
language: php

jobs:
  include:
    - php: 7.3
    - php: 7.4
    - php: 8.0
      env:
      - XDEBUG_MODE=coverage
      after_script:
      - wget https://scrutinizer-ci.com/ocular.phar
      - php ocular.phar code-coverage:upload --format=php-clover test/build/clover.xml

services:
  - postgresql
  - mysql

addons:
  postgresql: "9.5"

before_script:
  - 'composer install --dev --prefer-source'
  - psql -c 'create database mindplay_sql_test;' -U postgres
  - mysql -e 'CREATE DATABASE mindplay_sql_test;'

script: php test/test.php
